name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  frontend-lint:
    name: Frontend Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps

      - name: Run Lint
        run: |
          cd frontend
          npm install --legacy-peer-deps
          npm run lint

  backend-lint:
    name: Backend Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Lint
        run: |
          cd backend
          npm run lint

  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: frontend-lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps

      - name: Build Frontend
        run: |
          cd frontend
          npm install --legacy-peer-deps
          npm run build

  backend-test:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: backend-lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Tests
        run: |
          cd backend
          npm test